### ISSUE TITLE
error block not executing

### ISSUE THREAD

**Issue by ezazwar1** [Telerik-Verified-Plugins/SafariViewController#1]
Hey Great Plugin but have some problems in ionic 
1. error block not executing 
   2.readonly mode not working

**Comment by EddyVerbruggen** [comment]
Can you share your app perhaps and tell me what you tried and when this happens on which device(s)? I really need more details :)

**Comment by ezazwar1** [comment]
```
          if (href) {
                 SafariViewController.isAvailable(function (available) {
          if (available) {
            SafariViewController.show({
              url: href,
              hidden: false, // default false. You can use this to load cookies etc in the background
              animated: false, // default true, note that 'hide' will reuse this preference (the 'Done' button will always animate though)
              transition: 'curl', // unless animated is false you can choose from: curl, flip, fade, slide (default)
              tintColor: '#FF0000', // changes the button colors, default is iOS blue
                  },
                  function(result) {
                    console.log("Perfect");
                    },
                    function(msg) {
                   console.log("ladae puuns koul hehree"+msg);
                 window.open(href, "_blank", "closebuttoncaption=Done,location=no");
            })
                } else {
                  // potentially powered by InAppBrowser because that (currently) clobbers window.open
                  window.open(href, "_blank", "closebuttoncaption=Done,location=no");
                }
              });

          }
```

Working fine without the readonly mode otherwise doesnt work if readonly mode is set and the error message is not executed

**Comment by ezazwar1** [comment]
and transition effects are also not working in ionic

**Comment by ezazwar1** [comment]
**\* WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported

This error is logged in the console 
i guess the error function of the plugin should execute when such error is thrown but it doesnt seem to be working

**Comment by EddyVerbruggen** [comment]
What's the URL you're loading into SVC?

**Comment by ezazwar1** [comment]
any url be it tel:16627728, mailto:abc@abc.com or http and https
as svc only supports http and https they are working great but if i use tel:123456 i think the error block should execute but it does not

Anyways did it by checking whether the href contains tel,mailto or http or https and the  transition is not working and readonly mode is not working too in ionic framework 

BTW you are a genius
thanks for all great plugins

**Comment by EddyVerbruggen** [comment]
Thanks man!

Version 1.4.2 is now available and invokes the error callback when a non-http(s) URL is passed to the plugin.

**Comment by ezazwar1** [comment]
Hey @EddyVerbruggen  What about the transition effects and readonly mode they are not working 

maybe you should have a look 

Regards 
Ezaz

**Comment by EddyVerbruggen** [comment]
Ha, fun fact: custom transitions worked in iOS 9.1 but no longer in 9.3. Let's see if anything can be done about that..

**Comment by ezazwar1** [comment]
Great well what about the readmode i am unable to set the readmode

**Comment by EddyVerbruggen** [comment]
With `enterReaderModeIfAvailable : true` the site must have it available, otherwise it won't display reader mode. So which site are you loading? You can check if it support reader mode by loading the site in Safari, see the icon to the left of the lock icon:

<img width="311" alt="screen shot 2016-04-15 at 14 58 13" src="https://cloud.githubusercontent.com/assets/1426370/14567441/5cf3bfa8-0334-11e6-9c27-b63b207c541f.png">

**Comment by ezazwar1** [comment]
Thanks Man
